version: '3.9'
services:
  MININET_Server:
    image: georgepacheco/fotsolid:0.24
    deploy:
      resources:
        limits:
          memory: 3gb
        reservations:
          memory: 800mb
    container_name: MININET_SERVER
    volumes:
      - .:/fot-simulator/sensores
      - /lib/modules:/lib/modules
    working_dir: /fot-simulator
    env_file: ./local_docker.env
    environment:
     - PASTA_LOGS=/fot-simulator/sensores/devops/logs
    privileged: true
    networks:
      mqtt-mininet:
        ipv4_address: 222.222.222.3
        aliases:
          - server.mininet
    entrypoint: bash /fot-simulator/commands/inicializa_mininet.sh
    # entrypoint: sleep 1d
networks:
    mqtt-mininet:
      name: mqtt-mininet
      external: true
#      ipam:
#        driver: default
#        config:
#          - subnet: "222.222.222.0/24"

