version: '1.0'
services:
  SOLID_SERVER_S1:
    # image: georgepacheco/solid-server:1.1
    image: georgepacheco/solid-server:1.2
    container_name: SOLID_SERVER_S1
    volumes:
      - .:/solid-server
    expose:
      - "3000"
      - "3030"
    ports:
     - "3000:3000"
     - "3030:3030"
    networks:
      comm-mqtt:
        aliases:
          - server1.solid
      mqtt-mininet:
        ipv4_address: 222.222.222.9
        aliases:
          - server1.solid
    #entrypoint: npm start -- -c config/file.json -f .data
    # entrypoint: bash -c "npm start -- -c config/file.json -f .data & sleep 20 && python3 ../solid-server/server.py"
    entrypoint: bash -c "npm start -- -c config/file.json -f .data & sleep 20 && node ../solid-server/FotSolid/backend/dist/index.js && python3 ../solid-server/server.py"
networks:
  comm-mqtt:
    name: comm-mqtt
    external: true
  mqtt-mininet:
    name: mqtt-mininet
    external: true