services:
  SOLID_SERVER_S1:
    
    image: georgepacheco/dash-solid:1.2.2

    container_name: SOLID_SERVER_S1
    
    volumes:
      - .:/solid-server
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./FotSolid/fot-solid-dash/build:/usr/share/nginx/html/fot-solid-dash
      - ./FotSolid/health-application/build:/usr/share/nginx/html/health-application
      
      - ./certbot/conf:/etc/letsencrypt  # Monta os certificados
      - ./certbot/www:/var/www/certbot    # Monta o diretório do desafio ACME
    expose:
      - "3000"    
      - "3030"
      - "3001"
      - "3002"
      - "80"
    ports:
     - "3000:3000"     
     - "3001:3001"
     - "3002:3002"
     - "3030:3030"
     - "80:80"
    
    networks:
      comm-mqtt:
        aliases:
          - server1.solid
      mqtt-mininet:
        ipv4_address: 222.222.222.9
        aliases:
          - server1.solid        
    entrypoint: bash -c "npm start -- -b http://192.168.0.111:3000 -c config/file.json -f .data & sleep 20 & python3 ../solid-server/server.py & node ../solid-server/FotSolid/backend/dist/index.js & nginx -c /etc/nginx/nginx.conf -g 'daemon off;'"    
    # entrypoint: bash -c "npm start -- -c config/file.json -f .data & sleep 20 & python3 ../solid-server/server.py & node ../solid-server/FotSolid/backend/dist/index.js & nginx -c /etc/nginx/nginx.conf -g 'daemon off;'"    
    # entrypoint: bash -c "npm start -- -c config/file.json -f .data & sleep 20 & python3 ../solid-server/server.py & node ../solid-server/FotSolid/backend/dist/index.js"    
    
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt  # Monta o diretório para armazenar os certificados
      - ./certbot/www:/var/www/certbot    # Monta o diretório do desafio ACME
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  comm-mqtt:
    name: comm-mqtt
    external: true
  mqtt-mininet:
    name: mqtt-mininet
    external: true
