version: '3.8'
services:
  SOLID_SERVER_S1:
    # image: georgepacheco/solid-server:1.1
    # image: georgepacheco/solid-server:1.3
    image: georgepacheco/dash_solid:1.0
    container_name: SOLID_SERVER_S1
    # env_file:
    #   .env
    volumes:
      - .:/solid-server
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
    expose:
      - "3000"    
      - "3030"
      - "3001"
      - "3002"
    ports:
     - "3000:3000"     
     - "3001:3001"
     - "3002:3002"
     - "3030:3030"
    # restart: always
    networks:
      comm-mqtt:
        aliases:
          - server1.solid
      mqtt-mininet:
        ipv4_address: 222.222.222.9
        aliases:
          - server1.solid        
    entrypoint: bash -c "npm start -- -b http://10.27.0.62:3000 -c config/file.json -f .data & sleep 20 & python3 ../solid-server/server.py & node ../solid-server/FotSolid/backend/dist/index.js & nginx -c /etc/nginx/nginx.conf -g 'daemon off;'"    
    
networks:
  comm-mqtt:
    name: comm-mqtt
    external: true
  mqtt-mininet:
    name: mqtt-mininet
    external: true