version: '3'
services:
  GATEWAY_H1:
    image: georgepacheco/mqtt:0.1
    container_name: GATEWAY_H1
    volumes:
      - .:/mqtt-server/code
    working_dir: /mqtt-server
    hostname: g01
    expose:
      - "1883"
      - "9001"
    networks:
      comm-mqtt:
        aliases:
          - server1.mqtt
      mqtt-mininet:
        ipv4_address: 222.222.222.4 
        aliases:
          - server1.mqtt
    entrypoint: bash -c "mosquitto -c code/mosquitto-no-auth.conf & sleep 5 && pip install paho-mqtt==1.6.1 && sleep 10 && python3 code/mqtt-client.py 222.222.222.4 222.222.222.9"
    #entrypoint: bash -c "mosquitto -c code/mosquitto-no-auth.conf & sleep 5 && mosquitto_sub -t '#' > DATA.json"
    stdin_open: true 
      
networks:
  comm-mqtt:
    name: comm-mqtt
    driver: bridge
  mqtt-mininet:
    name: mqtt-mininet
    ipam:
      driver: default
      config:
        - subnet: "222.222.222.0/24"